-- ============================================
-- Migration 072: genre vocabulary clean-up
--
-- Catalog launch plan (2026-09-05) task 8. After the NYT / Open Library
-- imports `books.genres` held 7,141 distinct strings — Open Library subjects
-- and Google categories leaked through ("Fiction, Thrillers, General",
-- "Juvenile Fiction", "[document]", "11.93 Buddhism", "1835-1910") — and the
-- Browse page listed every one of them as a filter chip.
--
-- Part 1 rewrites every row's `genres` through the alias table below, which
-- is generated from `GENRE_ALIASES` in lib/data/genres.ts (the same mapping
-- every importer and the search-to-add action now apply on the way in).
-- Each string is split on `,` `/` `--` `;`, every part is looked up
-- case-insensitively, unknown parts are dropped, first-seen order is kept and
-- duplicates collapse. A row that would end up empty keeps what it had (the
-- 2026-09-07 dry run found none). Idempotent: vocabulary entries map onto
-- themselves.
--
-- Part 2 makes get_distinct_genres() (the Browse chip list, migration 047)
-- return genres by book count instead of alphabetically, so the first row of
-- chips is the biggest genres.
--
-- Usage:
--   npx supabase db query --linked -f supabase/migrations/072_genre_vocabulary.sql
-- ============================================

-- Part 1: map the existing rows -------------------------------------------

WITH alias(variant, canonical) AS (
  VALUES
    ('fiction', ARRAY['Fiction']),
    ('novel', ARRAY['Fiction']),
    ('novels', ARRAY['Fiction']),
    ('general fiction', ARRAY['Fiction']),
    ('fiction in english', ARRAY['Fiction']),
    ('american fiction', ARRAY['Fiction']),
    ('english fiction', ARRAY['Fiction']),
    ('ficción', ARRAY['Fiction']),
    ('romans', ARRAY['Fiction']),
    ('literary fiction', ARRAY['Literary Fiction']),
    ('literary', ARRAY['Literary Fiction']),
    ('contemporary fiction', ARRAY['Contemporary']),
    ('contemporary', ARRAY['Contemporary']),
    ('contemporary women', ARRAY['Contemporary']),
    ('historical fiction', ARRAY['Historical Fiction']),
    ('historical', ARRAY['Historical Fiction']),
    ('historical romance', ARRAY['Historical Fiction', 'Romance']),
    ('classics', ARRAY['Classics']),
    ('classic', ARRAY['Classics']),
    ('classic literature', ARRAY['Classics']),
    ('early works to 1800', ARRAY['Classics']),
    ('fantasy', ARRAY['Fantasy']),
    ('fantasy fiction', ARRAY['Fantasy']),
    ('epic fantasy', ARRAY['Fantasy']),
    ('high fantasy', ARRAY['Fantasy']),
    ('urban fantasy', ARRAY['Fantasy']),
    ('dark fantasy', ARRAY['Fantasy']),
    ('epic', ARRAY['Fantasy']),
    ('magic', ARRAY['Fantasy']),
    ('wizards', ARRAY['Fantasy']),
    ('dragons', ARRAY['Fantasy']),
    ('romantasy', ARRAY['Fantasy', 'Romance']),
    ('science fiction & fantasy', ARRAY['Science Fiction', 'Fantasy']),
    ('science fiction', ARRAY['Science Fiction']),
    ('science-fiction', ARRAY['Science Fiction']),
    ('sci-fi', ARRAY['Science Fiction']),
    ('scifi', ARRAY['Science Fiction']),
    ('american science fiction', ARRAY['Science Fiction']),
    ('english science fiction', ARRAY['Science Fiction']),
    ('space opera', ARRAY['Science Fiction']),
    ('time travel', ARRAY['Science Fiction']),
    ('life on other planets', ARRAY['Science Fiction']),
    ('space colonies', ARRAY['Science Fiction']),
    ('extraterrestrial beings', ARRAY['Science Fiction']),
    ('human-alien encounters', ARRAY['Science Fiction']),
    ('dystopian', ARRAY['Dystopian']),
    ('dystopias', ARRAY['Dystopian']),
    ('dystopia', ARRAY['Dystopian']),
    ('dystopian fiction', ARRAY['Dystopian']),
    ('paranormal', ARRAY['Paranormal']),
    ('paranormal fiction', ARRAY['Paranormal']),
    ('paranormal romance', ARRAY['Paranormal', 'Romance']),
    ('supernatural', ARRAY['Paranormal']),
    ('occult & supernatural', ARRAY['Paranormal']),
    ('vampires', ARRAY['Paranormal']),
    ('ghosts', ARRAY['Paranormal']),
    ('horror', ARRAY['Horror']),
    ('horror fiction', ARRAY['Horror']),
    ('horror tales', ARRAY['Horror']),
    ('horror stories', ARRAY['Horror']),
    ('american horror tales', ARRAY['Horror']),
    ('ghost stories', ARRAY['Horror']),
    ('zombies', ARRAY['Horror']),
    ('mystery', ARRAY['Mystery']),
    ('mysteries', ARRAY['Mystery']),
    ('mystery fiction', ARRAY['Mystery']),
    ('mystery & detective', ARRAY['Mystery']),
    ('detective and mystery stories', ARRAY['Mystery']),
    ('mystery and detective stories', ARRAY['Mystery']),
    ('detective', ARRAY['Mystery']),
    ('detectives', ARRAY['Mystery']),
    ('private investigators', ARRAY['Mystery']),
    ('women detectives', ARRAY['Mystery']),
    ('investigation', ARRAY['Mystery']),
    ('cozy mystery', ARRAY['Mystery']),
    ('mystery thriller', ARRAY['Mystery', 'Thriller']),
    ('thriller', ARRAY['Thriller']),
    ('thrillers', ARRAY['Thriller']),
    ('suspense', ARRAY['Thriller']),
    ('suspense fiction', ARRAY['Thriller']),
    ('psychological thriller', ARRAY['Thriller']),
    ('legal thriller', ARRAY['Thriller']),
    ('espionage', ARRAY['Thriller']),
    ('spies', ARRAY['Thriller']),
    ('crime', ARRAY['Crime']),
    ('crimes', ARRAY['Crime']),
    ('crime fiction', ARRAY['Crime']),
    ('murder', ARRAY['Crime']),
    ('murderers', ARRAY['Crime']),
    ('serial murders', ARRAY['Crime']),
    ('serial murderers', ARRAY['Crime']),
    ('homicide', ARRAY['Crime']),
    ('organized crime', ARRAY['Crime']),
    ('criminals', ARRAY['Crime']),
    ('romance', ARRAY['Romance']),
    ('romance fiction', ARRAY['Romance']),
    ('love stories', ARRAY['Romance']),
    ('man-woman relationships', ARRAY['Romance']),
    ('contemporary romance', ARRAY['Contemporary', 'Romance']),
    ('dark romance', ARRAY['Romance']),
    ('enemies to lovers', ARRAY['Romance']),
    ('adventure', ARRAY['Adventure']),
    ('adventure fiction', ARRAY['Adventure']),
    ('adventure stories', ARRAY['Adventure']),
    ('adventure and adventurers', ARRAY['Adventure']),
    ('action & adventure', ARRAY['Adventure']),
    ('action and adventure', ARRAY['Adventure']),
    ('expeditions', ARRAY['Adventure']),
    ('humor', ARRAY['Humor']),
    ('humour', ARRAY['Humor']),
    ('humorous', ARRAY['Humor']),
    ('humorous stories', ARRAY['Humor']),
    ('humorous fiction', ARRAY['Humor']),
    ('comedy', ARRAY['Humor']),
    ('satire', ARRAY['Humor']),
    ('short stories', ARRAY['Short Stories']),
    ('short story collections', ARRAY['Short Stories']),
    ('american short stories', ARRAY['Short Stories']),
    ('poetry', ARRAY['Poetry']),
    ('poems', ARRAY['Poetry']),
    ('american poetry', ARRAY['Poetry']),
    ('english poetry', ARRAY['Poetry']),
    ('drama', ARRAY['Drama']),
    ('plays', ARRAY['Drama']),
    ('theater', ARRAY['Drama']),
    ('graphic novel', ARRAY['Graphic Novel']),
    ('graphic novels', ARRAY['Graphic Novel']),
    ('comics & graphic novels', ARRAY['Graphic Novel']),
    ('comic books', ARRAY['Graphic Novel']),
    ('comics', ARRAY['Graphic Novel']),
    ('cartoons and comics', ARRAY['Graphic Novel']),
    ('manga', ARRAY['Graphic Novel']),
    ('mythology', ARRAY['Mythology']),
    ('greek mythology', ARRAY['Mythology']),
    ('myths', ARRAY['Mythology']),
    ('folklore', ARRAY['Mythology']),
    ('fairy tales', ARRAY['Mythology']),
    ('legends', ARRAY['Mythology']),
    ('retellings', ARRAY['Mythology']),
    ('young adult', ARRAY['Young Adult']),
    ('young adult fiction', ARRAY['Young Adult']),
    ('young adult nonfiction', ARRAY['Young Adult', 'Non-Fiction']),
    ('teen fiction', ARRAY['Young Adult']),
    ('ya', ARRAY['Young Adult']),
    ('children', ARRAY['Children']),
    ('children''s', ARRAY['Children']),
    ('childrens', ARRAY['Children']),
    ('children''s fiction', ARRAY['Children', 'Fiction']),
    ('children''s literature', ARRAY['Children']),
    ('children''s stories', ARRAY['Children']),
    ('children''s books', ARRAY['Children']),
    ('juvenile fiction', ARRAY['Children', 'Fiction']),
    ('juvenile literature', ARRAY['Children']),
    ('juvenile nonfiction', ARRAY['Children', 'Non-Fiction']),
    ('ficción juvenil', ARRAY['Children']),
    ('picture books', ARRAY['Children']),
    ('stories in rhyme', ARRAY['Children']),
    ('middle grade', ARRAY['Children']),
    ('readers', ARRAY['Children']),
    ('toy and movable books', ARRAY['Children']),
    ('board books', ARRAY['Children']),
    ('lgbtq+', ARRAY['LGBTQ+']),
    ('lgbt', ARRAY['LGBTQ+']),
    ('lgbtq', ARRAY['LGBTQ+']),
    ('lgbtqia+', ARRAY['LGBTQ+']),
    ('lgbtq novels', ARRAY['LGBTQ+']),
    ('queer', ARRAY['LGBTQ+']),
    ('gay', ARRAY['LGBTQ+']),
    ('gays', ARRAY['LGBTQ+']),
    ('gay men', ARRAY['LGBTQ+']),
    ('lesbian', ARRAY['LGBTQ+']),
    ('lesbians', ARRAY['LGBTQ+']),
    ('lesbianism', ARRAY['LGBTQ+']),
    ('homosexuality', ARRAY['LGBTQ+']),
    ('bisexual', ARRAY['LGBTQ+']),
    ('transgender people', ARRAY['LGBTQ+']),
    ('gender identity', ARRAY['LGBTQ+']),
    ('non-fiction', ARRAY['Non-Fiction']),
    ('nonfiction', ARRAY['Non-Fiction']),
    ('non fiction', ARRAY['Non-Fiction']),
    ('popular works', ARRAY['Non-Fiction']),
    ('biography', ARRAY['Biography']),
    ('biographies', ARRAY['Biography']),
    ('biography & autobiography', ARRAY['Biography']),
    ('autobiography', ARRAY['Biography']),
    ('autobiographies', ARRAY['Biography']),
    ('biografía', ARRAY['Biography']),
    ('memoir', ARRAY['Memoir']),
    ('memoirs', ARRAY['Memoir']),
    ('personal memoirs', ARRAY['Memoir']),
    ('personal narratives', ARRAY['Memoir']),
    ('diaries', ARRAY['Memoir']),
    ('history', ARRAY['History']),
    ('histoire', ARRAY['History']),
    ('world history', ARRAY['History']),
    ('military history', ARRAY['History']),
    ('world war', ARRAY['History']),
    ('civilization', ARRAY['History']),
    ('science', ARRAY['Science']),
    ('popular science', ARRAY['Science']),
    ('physics', ARRAY['Science']),
    ('astronomy', ARRAY['Science']),
    ('cosmology', ARRAY['Science']),
    ('biology', ARRAY['Science']),
    ('mathematics', ARRAY['Science']),
    ('genetics', ARRAY['Science']),
    ('evolution', ARRAY['Science']),
    ('nature', ARRAY['Science']),
    ('technology', ARRAY['Science']),
    ('neuroscience', ARRAY['Science']),
    ('psychology', ARRAY['Psychology']),
    ('brain', ARRAY['Psychology']),
    ('thought and thinking', ARRAY['Psychology']),
    ('philosophy', ARRAY['Philosophy']),
    ('ethics', ARRAY['Philosophy']),
    ('stoicism', ARRAY['Philosophy']),
    ('religion', ARRAY['Religion']),
    ('religious', ARRAY['Religion']),
    ('christianity', ARRAY['Religion']),
    ('christian life', ARRAY['Religion']),
    ('bible', ARRAY['Religion']),
    ('spirituality', ARRAY['Religion']),
    ('spiritual life', ARRAY['Religion']),
    ('buddhism', ARRAY['Religion']),
    ('islam', ARRAY['Religion']),
    ('judaism', ARRAY['Religion']),
    ('theology', ARRAY['Religion']),
    ('self-help', ARRAY['Self-Help']),
    ('self help', ARRAY['Self-Help']),
    ('selfhelp', ARRAY['Self-Help']),
    ('self-improvement', ARRAY['Self-Help']),
    ('self improvement', ARRAY['Self-Help']),
    ('personal development', ARRAY['Self-Help']),
    ('personal growth', ARRAY['Self-Help']),
    ('conduct of life', ARRAY['Self-Help']),
    ('self-help techniques', ARRAY['Self-Help']),
    ('self-realization', ARRAY['Self-Help']),
    ('success', ARRAY['Self-Help']),
    ('happiness', ARRAY['Self-Help']),
    ('motivational', ARRAY['Self-Help']),
    ('business', ARRAY['Business']),
    ('business & economics', ARRAY['Business']),
    ('entrepreneurship', ARRAY['Business']),
    ('management', ARRAY['Business']),
    ('leadership', ARRAY['Business']),
    ('marketing', ARRAY['Business']),
    ('finance', ARRAY['Business']),
    ('investments', ARRAY['Business']),
    ('success in business', ARRAY['Business']),
    ('careers', ARRAY['Business']),
    ('politics', ARRAY['Politics']),
    ('political', ARRAY['Politics']),
    ('political science', ARRAY['Politics']),
    ('politics and government', ARRAY['Politics']),
    ('government', ARRAY['Politics']),
    ('election', ARRAY['Politics']),
    ('political corruption', ARRAY['Politics']),
    ('political culture', ARRAY['Politics']),
    ('current events', ARRAY['Politics']),
    ('social science', ARRAY['Social Science']),
    ('social sciences', ARRAY['Social Science']),
    ('sociology', ARRAY['Social Science']),
    ('social conditions', ARRAY['Social Science']),
    ('race relations', ARRAY['Social Science']),
    ('racism', ARRAY['Social Science']),
    ('race', ARRAY['Social Science']),
    ('feminism', ARRAY['Social Science']),
    ('culture', ARRAY['Social Science']),
    ('popular culture', ARRAY['Social Science']),
    ('education', ARRAY['Social Science']),
    ('anthropology', ARRAY['Social Science']),
    ('economics', ARRAY['Social Science']),
    ('gender studies', ARRAY['Social Science']),
    ('women''s studies', ARRAY['Social Science']),
    ('true crime', ARRAY['True Crime']),
    ('trials (murder)', ARRAY['True Crime']),
    ('travel', ARRAY['Travel']),
    ('description and travel', ARRAY['Travel']),
    ('travel writing', ARRAY['Travel']),
    ('guidebooks', ARRAY['Travel']),
    ('cooking', ARRAY['Cooking']),
    ('cookery', ARRAY['Cooking']),
    ('cookbooks', ARRAY['Cooking']),
    ('recipes', ARRAY['Cooking']),
    ('american cooking', ARRAY['Cooking']),
    ('food', ARRAY['Cooking']),
    ('baking', ARRAY['Cooking']),
    ('food & fitness', ARRAY['Cooking', 'Health']),
    ('health', ARRAY['Health']),
    ('health & fitness', ARRAY['Health']),
    ('fitness', ARRAY['Health']),
    ('nutrition', ARRAY['Health']),
    ('diet', ARRAY['Health']),
    ('reducing diets', ARRAY['Health']),
    ('medicine', ARRAY['Health']),
    ('medical', ARRAY['Health']),
    ('mental health', ARRAY['Health']),
    ('wellness', ARRAY['Health']),
    ('mind & body', ARRAY['Health']),
    ('sports', ARRAY['Sports']),
    ('sports & recreation', ARRAY['Sports']),
    ('football', ARRAY['Sports']),
    ('baseball', ARRAY['Sports']),
    ('basketball', ARRAY['Sports']),
    ('soccer', ARRAY['Sports']),
    ('running', ARRAY['Sports']),
    ('athletes', ARRAY['Sports']),
    ('essays', ARRAY['Essays']),
    ('essay', ARRAY['Essays']),
    ('american essays', ARRAY['Essays']),
    ('english essays', ARRAY['Essays']),
    ('essays (single author)', ARRAY['Essays']),
    ('bestseller', ARRAY['Bestseller']),
    ('pulitzer prize', ARRAY['Pulitzer Prize']),
    ('hugo award', ARRAY['Hugo Award']),
    ('booker prize', ARRAY['Booker Prize']),
    ('national book award', ARRAY['National Book Award']),
    ('newbery medal', ARRAY['Newbery Medal']),
    ('caldecott medal', ARRAY['Caldecott Medal']),
    ('nebula award', ARRAY['Nebula Award']),
    ('women''s prize for fiction', ARRAY['Women''s Prize for Fiction']),
    ('international booker prize', ARRAY['International Booker Prize'])
),
parts AS (
  SELECT b.id, g.ord AS gord, p.ord AS pord,
         lower(regexp_replace(btrim(regexp_replace(translate(p.part, '’‘', ''''''), '\s+', ' ', 'g')), '\.$', '')) AS key
  FROM public.books b
  CROSS JOIN LATERAL unnest(b.genres) WITH ORDINALITY g(genre, ord)
  CROSS JOIN LATERAL regexp_split_to_table(g.genre, '\s*(,|/|--|;)\s*') WITH ORDINALITY p(part, ord)
),
hits AS (
  SELECT p.id, c.genre, min(p.gord * 1000000 + p.pord * 1000 + c.ord) AS pos
  FROM parts p
  JOIN alias a ON a.variant = p.key
  CROSS JOIN LATERAL unnest(a.canonical) WITH ORDINALITY c(genre, ord)
  GROUP BY p.id, c.genre
),
mapped AS (
  SELECT id, array_agg(genre ORDER BY pos) AS genres FROM hits GROUP BY id
)
UPDATE public.books b
SET genres = m.genres
FROM mapped m
WHERE m.id = b.id
  AND b.genres IS DISTINCT FROM m.genres;

-- Part 2: Browse chips ordered by book count --------------------------------

CREATE OR REPLACE FUNCTION public.get_distinct_genres()
RETURNS TABLE(genre text)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT g AS genre
  FROM public.books, unnest(genres) AS g
  GROUP BY g
  ORDER BY count(*) DESC, g;
$$;

-- Check: distinct genre strings left (expected ~51) and rows with no genre (expected 0)
SELECT
  (SELECT count(DISTINCT g) FROM public.books, unnest(genres) g) AS distinct_genres,
  (SELECT count(*) FROM public.books WHERE genres IS NULL OR cardinality(genres) = 0) AS empty_rows;
